name: thesedays
description: Flutter long-time photo shooting.
version: 0.9.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  camera: ^0.9.4+21
  path_provider: ^2.0.8
  gallery_saver: ^2.3.2

  permission_handler: ^9.0.2
  photo_manager: ^2.0.9
  photo_gallery: ^1.1.1
  intl: ^0.17.0
  disk_space: ^0.2.1
  shared_preferences: ^2.0.13
  battery_plus: ^2.1.0

  record: ^4.4.1
  file_saver: ^0.1.1
  video_thumbnail: ^0.5.0
  video_player: ^2.4.7
  flutter_video_info: ^1.2.0

  image: ^3.1.3
  flutter_native_splash: ^1.3.1
  hooks_riverpod: ^1.0.3
  native_device_orientation: ^1.1.4
  wakelock: ^0.6.1+2

  googleapis: ^8.1.0
  google_sign_in: ^5.3.0
  google_sign_in_web: ^0.10.2
  extension_google_sign_in_as_googleapis_auth: ^2.0.4
  flutter_secure_storage: ^5.0.2
  in_app_purchase: ^3.0.6
  flutter_advanced_segment: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/test.jpg
